name: Output
on: push
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Setup output var
        id: test1
        run: |
          echo "TEST=first line \
          second line \
          third line" >> $GITHUB_OUTPUT
      - name: Check output var
        run: echo ${{steps.test1.outputs.TEST}}
