name: Output
on: push
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Setup output var0
        id: test0
        run: |
          MESSAGE=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          echo TEST0=$MESSAGE >> $GITHUB_OUTPUT
      - name: Check output var0
        run: echo ${{steps.test0.outputs.TEST0}}
      - name: Setup output var1
        id: test1
        run: |
          echo "TEST1=first line \
          second line \
          third line" >> $GITHUB_OUTPUT
      - name: Check output var1
        run: echo ${{steps.test1.outputs.TEST1}}
      - name: Setup output var2
        id: test2
        run: echo "TEST2=first line\n second line\n third line" >> $GITHUB_OUTPUT
      - name: Check output var2
        run: echo ${{steps.test2.outputs.TEST2}}
      - name: Setup output var3
        id: test3
        run: echo -e "TEST3=\"first line\n second line\n third line\"" >> $GITHUB_OUTPUT
      - name: Check output var3
        run: echo ${{steps.test3.outputs.TEST3}}
      - name: Setup output var4
        id: test4
        run: sh -c 'echo -e "TEST4=first line\n second line\n third line" >> $GITHUB_OUTPUT'
      - name: Check output var4
        run: echo ${{steps.test4.outputs.TEST4}}
