name: Output
on: push
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Setup output var1
        id: test1
        run: |
          echo "TEST1=first line \
          second line \
          third line" >> $GITHUB_OUTPUT
      - name: Check output var1
        run: echo ${{steps.test1.outputs.TEST1}}
      - name: Setup output var2
        id: test2
        run: echo "TEST2=first line\n second line\n third line" >> $GITHUB_OUTPUT
      - name: Check output var2
        run: echo ${{steps.test2.outputs.TEST2}}
